encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki", views.index, name="index"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("edit", views.edit, name="edit"),
    path("random", views.random, name="random"),
    path("error", views.error, name="error"),
    path("wiki/<str:name>", views.title, name="title")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    path('wiki/', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from encyclopedia import urls
from . import util

def index(request): #index page
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def title(request, name):
    if request.method == "POST": #editing page
        title = request.POST['t']
        content = request.POST['c']
        util.save_entry(title, content)
        if content.isspace() or content == "":
            return render(request, "encyclopedia/edit_page.html",{
            "title": util.title_change(title),
            "error": "Content is empty",
            })
        else:
            return render(request, "encyclopedia/entry_page.html", {
                "title": util.title_change(title),
                "content": util.get_entry(title),  
            })
    else: #for url search
        if util.title_change(name) == "None":  #url error
            return error(request)
        else: #redirect to existing entry
            return render(request, "encyclopedia/entry_page.html",{
                "title": util.title_change(name),
                "content": util.get_entry(name), 
            })

def search(request):
    # Check if method is POST
    if request.method == "GET":
        query = request.GET['q']
        store = util.search_entry(query, 0)
        substring = util.substring_check(query)
        if len(store) > 1 or substring == "true":  #contains substring 
            return render(request, "encyclopedia/search_page.html", {
                "queries": util.search_entry(query, 0),
                "title": "Pages containing " + "'" + query + "'",
            }) 
        elif len(store) == 0: #no results
            return render(request, "encyclopedia/search_page.html", {
                "queries": util.search_entry(query, 0),
                "title": "No results to show for " + "'" + query + "'"
            })
        else: #show entry page
            return render(request, "encyclopedia/entry_page.html", {
                "title": util.title_change(store[0]),
                "content": util.get_entry(store[0]), 
            }) 

def create(request):
    if request.method == "POST": #creates new page
        title = request.POST['t']
        content = request.POST['c']
        store = util.search_entry(title, 2)
        if store == "true":
            if title.isspace() or title == "":
                return render(request, "encyclopedia/new_page.html",{
                "t_error": "Title is empty",
                })
            elif content.isspace() or content == "":
                return render(request, "encyclopedia/new_page.html",{
                "c_error": "Content is empty",
                })
            else: #save entry, redirects to entry page
                content = "<h1>" + title + "</h1>" + content #uniform with sample entries
                util.save_entry(title, content)
                return render(request, "encyclopedia/entry_page.html", {
                    "title": title,
                    "content": content, 
                }) 
        else:
            return render(request, "encyclopedia/new_page.html",{
                "t_error": "'" + title + "'" +" is taken",
            })
    else:
      return render(request, "encyclopedia/new_page.html",{})
         
def edit(request): #after clicking edit button
    if request.method == "GET":
        title = request.GET['t']
        return render(request, "encyclopedia/edit_page.html", {
            "title": util.title_change(title),
            "content": util.get_entry(title),  
        })

def random(request):
    import random
    entry = random.choice(util.list_entries())
    return render(request, "encyclopedia/entry_page.html",{
        "title": util.title_change(entry),
        "content": util.get_entry(entry), 
    })

def error(request):
     return render(request, "encyclopedia/error_page.html",{})

encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
    <h3>Edit Page</h3>
    <form action="{% url 'main:title' title %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="t" value="{{ title }}" />
        <h3>{{ title }}</h3>
        <div>
            <textarea placeholder="Enter content here" name="c">{{ content }}</textarea>
        </div>
        <button> Save </button> <span>{{ error }}</span>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
    <form action="{% url 'main:edit' %}" method="GET">
        <input type="hidden" name="t" value="{{ title }}" />
        <input type="hidden" name="c" value="{{ content }}" />
        <div> 
            {{ content|safe }}
        </div>
        <button>Edit Page</button>
    </form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/error_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
        <h3>Requested page was not found</h3>    
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'main:title' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2 >Wiki</h2>
                <form action="/search" method="GET">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'main:index' %}">Home</a>
                </div>
                    <a href="{% url 'main:create' %}"> Create New Page</a>
                <div>
                    <a href="{% url 'main:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
    <h3>Create a New Page</h3>
    <form action="{% url 'main:create' %}" method="POST">
        {% csrf_token %}
        <input class="title" type="text" name="t" placeholder="Title here">
        <span>{{ t_error }}</span>
        <div>
            <textarea name="c" placeholder="Enter content here"></textarea>
        </div> 
        <button> Save </button> <span>{{ c_error }}</span>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/search_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block nav %}
{% endblock %}

{% block body %}
    <h3>{{ title }}</h3>
    {% for query in queries %}
        <a href="{% url 'main:title' query %}"><h3>{{ query }}</h3></a>
    {% endfor %}

{% endblock %}